# .bashrc
# THIS FILE DEPLOYED VIA CHEF 'station' cookbook

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

# Uncomment the following line if you don't like systemctl's auto-paging feature:
# export SYSTEMD_PAGER=

# User specific aliases and functions

# CUSTOM PATH
PATH=$PATH:/home/maxwell/.gem/bin

# Basic settings
. /usr/local/etc/shell-basics

# History related
. /usr/local/etc/shell-history

# Prompt related
. /usr/local/etc/shell-prompt-powerline

alias gitproj="cd /home/maxwell/projects/github/maxwax"

alias maxlab="cd /home/maxwell/projects/chef/maxlab"
alias maxbooks="cd /home/maxwell/projects/chef/maxlab/cookbooks"
alias maxroles="cd /home/maxwell/projects/chef/maxlab/roles"
alias maxbags="cd /home/maxwell/projects/chef/maxlab/data_bags"
alias maxenv="cd /home/maxwell/projects/chef/maxlab/environments"

alias atlab="cd /home/maxwell/projects/chef/atlab"
alias station="cd /home/maxwell/projects/chef/station"
alias update-workstation="station; sudo chef-client -z"

alias bc="bc -q"
export BC_ENV_ARGS=$HOME/.bcrc

export EDITOR="vim"

# ----------
# 2020-01-24 'chef shell-init bash'
export PATH="/opt/chef-workstation/bin:/home/maxwell/.chefdk/gem/ruby/2.6.0/bin:/opt/chef-workstation/embedded/bin:/usr/share/Modules/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/home/maxwell/.gem/bin:/home/maxwell/.local/bin:/home/maxwell/bin:/home/maxwell/.gem/bin:/opt/chef-workstation/gitbin"
export GEM_ROOT="/opt/chef-workstation/embedded/lib/ruby/gems/2.6.0"
export GEM_HOME="/home/maxwell/.chefdk/gem/ruby/2.6.0"
export GEM_PATH="/home/maxwell/.chefdk/gem/ruby/2.6.0:/opt/chef-workstation/embedded/lib/ruby/gems/2.6.0"
_chef_comp() {
    local COMMANDS="exec env gem generate shell-init install update push push-archive show-policy diff export clean-policy-revisions clean-policy-cookbooks delete-policy-group delete-policy undelete describe-cookbook provision"
    COMPREPLY=($(compgen -W "$COMMANDS" -- ${COMP_WORDS[COMP_CWORD]} ))
}
complete -F _chef_comp chef
# ----------
