#!/bin/bash
# THIS FILE DEPLOYED VIA CHEF 'station' cookbook

#
# Custom Prompt
#

if [[ $TERM != "vt220" ]]
then

  if [ -f `which powerline-daemon` ]; then
    powerline-daemon -q
    export POWERLINE_LOCATION="/usr/share/powerline"
    export POWERLINE_CONFIG="powerline-config"
    export POWERLINE_BASH_CONTINUATION=1
    export POWERLINE_BASH_SELECT=1

    . /usr/share/powerline/bash/powerline.sh
  fi
fi
