#!/bin/bash
# THIS FILE DEPLOYED VIA CHEF 'station' cookbook

#
# Custom Prompt
#

if [[ $TERM != "vt220" ]]
then

  if [ -f `which powerline-daemon` ]; then
    powerline-daemon -q
    POWERLINE_BASH_CONTINUATION=1
    POWERLINE_BASH_SELECT=1
    . /usr/share/powerline/bash/powerline.sh
  fi
fi
