#!/bin/bash
# THIS FILE DEPLOYED VIA CHEF 'station' cookbook

#
# UNLIMITED HISTORY, UNLIMITED HISTORY FILE SIZE
#

# When exiting a shell, append the exiting shell's history to the history file
shopt -s histappend

# Unlimited history stored in memory
export HISTSIZE=

# Unlimited history stored in .history file
export HISTFILESIZE=

# Erase duplicates
export HISTCONTROL=erasedups

# Store date time stamp with each command, show it with 'history' command
export HISTTIMEFORMAT="[%F %T] "

# Record history to an alternate file because some things truncate .bash_history
export HISTFILE=~/.bash_history_eternal
