# .bashrc

# User specific aliases and functions

alias rm='rm -i'
alias cp='cp -i'
alias mv='mv -i'

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

# Basic settings
. /usr/local/etc/shell-basics

# History related
. /usr/local/etc/shell-history

# Powerline prompt
. /usr/local/etc/shell-prompt-powerline
